export const enum Header {
    LOAD_STRING,
    LOAD_NUMBER,
    POP_STACK,
    FETCH_VARIABLE,
    FETCH_DEPENDENCY,
    LOAD_UNDEFINED,
    LOAD_ARRAY,
    LOAD_OBJECT,
}

export const enum Opcode {
    ADD,
    SUB,
    MUL,
    DIV,
    MOD,
    NEG,
    STORE,
    GET_PROPERTY,
    SET_PROPERTY,
    EXISTS,
    DELETE_PROPERTY,
    IN,
    INSTANCE_OF,
    TYPEOF,
    CALL,
    EQUAL,
    NOT_EQUAL,
    LESS_THAN,
    LESS_THAN_EQUAL,
    STRICT_EQUAL,
    STRICT_NOT_EQUAL,
    GREATER_THAN,
    GREATER_THAN_EQUAL,
    JMP_IF_ELSE,
    AND,
    OR,
    NOT,
    BITWISE_AND,
    BITWISE_OR,
    BITWISE_XOR,
    BITWISE_LEFT_SHIFT,
    BITWISE_RIGHT_SHIFT,
    BITWISE_UNSIGNED_RIGHT_SHIFT,
    PUSH,
    POP,
    INIT_CONSTRUCTOR,
    INIT_ARRAY,
    EXIT,
    VOID,
    THROW,
    DELETE,
    APPLY,
    CALL_MEMBER_EXPRESSION,
}

export const Dependency = [Array, ArrayBuffer, Atomics, Boolean, DataView, Date, Error, EvalError,
    Float32Array, Float64Array, Function, Infinity, Int16Array,
    Int32Array, Int8Array, JSON, Map, Math, NaN, Number, Object,
    Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set,
    String, Symbol, SyntaxError, TypeError, URIError,
    Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, console,
    decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, eval, isFinite,
    isNaN, parseFloat, parseInt, undefined, unescape, 'window']